Asylum/Controllers/PatientController.cs
using System.IO;
using System.Net;
using System.Web;
using System.Linq;
using Asylum.Model;
using System.Web.Mvc;
using Asylum.Model.ViewModels;
using System.Data.Entity;
using System.Collections.Generic;

namespace Asylum.Controller
{
    public class PatientController : System.Web.Mvc.Controller
    {
        private  ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Patient
        public ActionResult Index()
        {
            var patients = db.Patients.Include(i => i.Doctor).ToList();
            var vms = new List<PatientVm>();

            foreach (var patient in patients)
            {
                vms.Add(new PatientVm()
                {
                    Id = patient.Id,
                    Title = patient.Title,
                    FirstName = patient.FirstName,
                    LastName = patient.LastName,
                    Gender = patient.Gender,
                    DateOfBirth = patient.DateOfBirth,
                    DateOfAdmission = patient.DateOfAdmission,
                    Doctor = patient.Doctor
                });
            }
            return View(vms);            
        }

        // GET: Patient/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var patient = db.Patients
                .Include(i => i.Doctor)
                .Single(i => i.Id == id);


            if (patient == null)
            {
                return HttpNotFound();
            }

            var vm = new PatientVm
            {
                Id = patient.Id,
                Title = patient.Title,
                FirstName = patient.FirstName,
                LastName = patient.LastName,
                Gender = patient.Gender,
                DateOfBirth = patient.DateOfBirth,
                DateOfAdmission = patient.DateOfAdmission,
                Doctor = patient.Doctor,
                Photo = patient.Photo,
                Image = patient.Image,
                Medications = patient.Medications,
                Doctors = patient.Doctors

            };
            return View(vm);            
        }

        // GET: Patient/Create
        public ActionResult Create()
        {            
            ViewBag.DoctorId = new SelectList(db.Doctors, "ID", "FullName");
            return View();
        }

        //POST: Patient/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,FirstName,LastName,DateOfBirth,Gender,DateOfAdmission,Image,Photo,DoctorId")] Patient patientModel, HttpPostedFileBase file)
        {
            var newPatient = new PatientVm();

            if (ModelState.IsValid)
            {

                // Update fields
                if (file != null && file.ContentLength > 0)
                {
                    byte[] imgBinaryData = new byte[file.ContentLength];
                    patientModel.Image = imgBinaryData;
                    file.InputStream.Read(patientModel.Image, 0, file.ContentLength);
                    patientModel.Photo = Path.GetFileName(file.FileName);
                }

                newPatient.Title = patientModel.Title;
                newPatient.Gender = patientModel.Gender;
                newPatient.FirstName = patientModel.FirstName;
                newPatient.LastName = patientModel.LastName;
                newPatient.DateOfAdmission = patientModel.DateOfAdmission;
                newPatient.DateOfBirth = patientModel.DateOfBirth;
                newPatient.DoctorId = patientModel.DoctorId;
                newPatient.Doctor = patientModel.Doctor;

                db.Patients.Add(patientModel);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DoctorId = new SelectList(db.Doctors, "ID", "FullName", patientModel.DoctorId);
            return View(newPatient);
            
        }

        // GET: Patient/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var patient = db.Patients
                .Include(i => i.Medications)
                .Single(i => i.Id == id);
            PopulatePrescribedMedicationData(patient);

            if (patient == null)
            {
                return HttpNotFound();
            }

            PatientVm vm = new PatientVm
            {
                Id = patient.Id,
                Title = patient.Title,
                FirstName = patient.FirstName,
                LastName = patient.LastName,
                Gender = patient.Gender,
                DateOfBirth = patient.DateOfBirth,
                DateOfAdmission = patient.DateOfAdmission,
                Doctor = patient.Doctor,
                Photo = patient.Photo,
                Image = patient.Image,
                Medications = patient.Medications,
                Doctors = patient.Doctors,
                DoctorId = patient.DoctorId
            };

            //Used by the drop down list
            ViewBag.DoctorId = new SelectList(db.Doctors, "ID", "FullName", vm.DoctorId);

            return View(vm);
            
        }

        private void PopulatePrescribedMedicationData(Patient patient)
        {
            var allMedications = db.Medications;
            var patientMedications = new HashSet<int>(patient.Medications.Select(c => c.ID));
            var viewModel = new List<PrescribedMedicationData>();
            foreach (var medication in allMedications)
            {
                viewModel.Add(new PrescribedMedicationData
                {
                    MedicationID = medication.ID,
                    Manufacturer = medication.Manufacturer,
                    Name = medication.Name,
                    Dosage = medication.Dosage,
                    Prescribed = patientMedications.Contains(medication.ID)
                });
            }
            ViewBag.Medications = viewModel;
        }

        // POST: Patient/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Exclude = "Image")]PatientVm vm, HttpPostedFileBase file, string[] selectedMedications)
        {
            //Uncomment the following if statement and code block if you wish to save a copy of the file to folder
            //if (file != null && file.ContentLength > 0)
            //{
            // extract only the fieldname
            //var fileName = Path.GetFileName(file.FileName);
            // store the file inside ~/App_Data/Profiles/Mugshots folder
            //var path = Path.Combine(Server.MapPath("~/App_Data/Profiles/Mugshots"), fileName);
            //file.SaveAs(path);
            //}

            if (ModelState.IsValid)
            {
                // Get the patient to update             
                var patientToUpdate = db.Patients
                    .Include(i => i.Medications)
                    .Single(i => i.Id == vm.Id);

                // Update fields
                if (file != null && file.ContentLength > 0)
                {
                    var imgBinaryData = new byte[file.ContentLength];
                    patientToUpdate.Image = imgBinaryData;
                    file.InputStream.Read(patientToUpdate.Image, 0, file.ContentLength);
                    patientToUpdate.Photo = Path.GetFileName(file.FileName);
                }

                patientToUpdate.Title = vm.Title;
                patientToUpdate.Gender = vm.Gender;
                patientToUpdate.FirstName = vm.FirstName;
                patientToUpdate.LastName = vm.LastName;
                patientToUpdate.DateOfAdmission = vm.DateOfAdmission;
                patientToUpdate.DateOfBirth = vm.DateOfBirth;
                patientToUpdate.DoctorId = vm.DoctorId;
                patientToUpdate.Doctor = vm.Doctor;

                db.Entry(patientToUpdate).State = EntityState.Modified;
                
                UpdatePatientMedications(selectedMedications, patientToUpdate);
                
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.DoctorId = new SelectList(db.Doctors, "ID", "Title", vm.DoctorId);

            return View(vm);            
        }

        public void UpdatePatientMedications(string[] selectedMedications, Patient patientToUpdate)
        {
            if (selectedMedications == null)
            {
                patientToUpdate.Medications = new List<Medication>();
                return;
            }

            var selectedMedicationsHs = new HashSet<string>(selectedMedications);
            var patientMedications = new HashSet<int>(patientToUpdate.Medications.Select(c => c.ID));
            foreach (var medication in db.Medications)
            {
                if (selectedMedicationsHs.Contains(medication.ID.ToString()))
                {
                    if (!patientMedications.Contains(medication.ID))
                    {
                        patientToUpdate.Medications.Add(medication);
                    }
                }
                else
                {
                    if (patientMedications.Contains(medication.ID))
                    {
                        patientToUpdate.Medications.Remove(medication);
                    }
                }
            }
        }

        // GET: Patient/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }

            PatientVm VM = new PatientVm
            {

Asylum/Views/Patient/Create.cshtml
@model Asylum.Model.ViewModels.PatientVm
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Register New Patient</h2>

@using (Html.BeginForm("Create", "Patient", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfAdmission, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfAdmission, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfAdmission, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorId, "Doctor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DoctorId, (IEnumerable<SelectListItem>)ViewBag.Doctors, "--Select--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DoctorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, "Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" accept=".png,.jpg,.jpeg,.gif,.tif" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Asylum/Views/Patient/Delete.cshtml
@model Asylum.Model.ViewModels.PatientVm

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Are you sure you want to delete @Html.DisplayFor(model => model.FullName)'s record?</h3>

<div>    
    <hr />
    <dl class="dl-horizontal">        
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfAdmission)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfAdmission)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Asylum/Views/Patient/Details.cshtml
@model Asylum.Model.ViewModels.PatientVm

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h4>Detailed information on : @Html.DisplayName(Model.FullName)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfAdmission)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfAdmission)
        </dd>

        <dt>
            Doctor
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doctor.FullName)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @if (Model.Image != null)
            {
                <img src="data:image;base64,@Convert.ToBase64String(Model.Image)" width="200" alt="Sorry"/>
            }
            else
            {
                <img src="~/Content/Images/NoProfile.jpg" width="200" alt="Sorry"/>
            }

        </dd>
    </dl>
    <dl>
        <dd>
            <table class="table">
                <tr>
                    <th colspan="3">Prescribed Medications</th>
                </tr>
                <tr>
                    <th>Manufaturer</th>
                    <th>Name</th>
                    <th>Dosage</th>
                </tr>
                @foreach (var item in Model.Medications)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Manufacturer)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Dosage)
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Asylum/Views/Patient/Edit.cshtml
@model Asylum.Model.ViewModels.PatientVm

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editing : @Html.DisplayFor(model => model.FullName)</h2>

@using (Html.BeginForm("Edit", "Patient", FormMethod.Post, new {enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.LastName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-3">
                @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.TextBoxFor(m => m.DateOfBirth, "{0:yyyy-MM-dd}", htmlAttributes: new { type = "date", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new {@class = "text-danger"})
            </div>
        
            @Html.LabelFor(model => model.DateOfAdmission, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.TextBoxFor(m => m.DateOfAdmission, "{0:yyyy-MM-dd}", htmlAttributes: new { type = "date", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DateOfAdmission, "", new {@class = "text-danger"})
            </div>
        </div>
        
        <div class="form-group">
                        
            @Html.LabelFor(model => model.DoctorId, "Doctor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.DropDownListFor(model => model.DoctorId, (IEnumerable<SelectListItem>)ViewBag.Doctors, "--Select--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DoctorId, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Photo, "Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">                
                <input type="file" name="file" id="file" accept=".png,.jpg,.jpeg,.gif,.tif" />
                @if (Model.Image != null)
                {
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    <img src="data:image;base64,@Convert.ToBase64String(Model.Image)" width="200" />
                }
                else
                {
                    <img src="~/Content/Images/NoProfile.jpg" width="200" />
                }
                </div>
            </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<Asylum.Model.PrescribedMedicationData> medications = ViewBag.Medications;

                            foreach (var medication in medications)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td style="padding:10px">&nbsp;
                                    <input type="checkbox" name="selectedMedications" value="@medication.MedicationID" @(Html.Raw(medication.Prescribed ? "checked=\"checked\"" : "")) />
                                    @medication.Name
                                @:</td>
                            }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Asylum/Views/Patient/Index.cshtml
@model IEnumerable<Asylum.Model.ViewModels.PatientVm>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registered Patients</h2>

<p>
    @Html.ActionLink("Register new patient", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th> 
        <th>
            Assigned Doctor
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfAdmission)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>        
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>   
        <td>
            @Html.DisplayFor(modelItem => item.Doctor.FullName)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfAdmission)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>